name: build_Qt5.15.16_MinGW810_32

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 5.15.16
  QT_VERSION2: 5.15
  FILE_NAME: Qt_5.15.16-shared-Debug_mingw810_32

jobs:
  windows_mingw32_shared_debug:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 Perl    
    - name: Setup Perl
      run: |
        cd ..  #Directory: D:\a\buildQt
        curl -L -o strawberry-perl-64bit-portable.zip https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip
        unzip -q strawberry-perl-64bit-portable.zip -d ./Strawberry

    # 安装 MinGW810_32    
    - name: Setup MinGW32
      run: |
        cd ..  #Directory: D:\a\buildQt
        mkdir -p mingw32
        curl -L -o 8.1.0-release-posix-seh.7z https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw81/qt.tools.win32_mingw810/8.1.0-1-202411201005i686-8.1.0-gdb-11.2.0-release-posix-dwarf-rt_v6-rev0.7z
        7z x D:\a\buildQt\8.1.0-release-posix-seh.7z -oD:\a\buildQt\mingw32

    # 构建Qt
    - name: Build Qt
      run: |
        #ls     #Directory: D:\a\buildQt\buildQt(即仓库目录)
        #D:\a\buildQt                                上级目录，这里当做根目录
        #D:\a\buildQt\Qt                             Qt目录
        #D:\a\buildQt\Qt\${{env.QT_VERSION}}         Qt目录源代码和build文件夹存放目录
        #D:\a\buildQt\Qt\${{env.QT_VERSION}}-shared  Qt安装目录
        
        # 创建文件夹
        cd ..  #Directory: D:\a\buildQt
        mkdir -p Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\buildQt\Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-shared

        # 下载源代码并解压，源代码目录D:\a\buildQt\Qt\${{env.QT_VERSION}}\XXX
        curl -L -o qt-everywhere-opensource-src.zip https://download.qt.io/archive/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-opensource-src-${{env.QT_VERSION}}.zip
        unzip -q qt-everywhere-opensource-src.zip -d ./${{env.QT_VERSION}}

        # 调用编译脚本
        cmd.exe /c "call `"D:\a\buildQt\buildQt\buildQt5\build-Qt5mingw810_32`""

    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\buildQt\buildQt(即仓库目录)
        7z a ${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-shared -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: ${{env.FILE_NAME}}
        path: ${{env.FILE_NAME}}.7z
